# .chglog/config.yml
title: "Changelog"
repository_url: "https://github.com/mvleandro/chronolog"

sections:
  - title: "âœ¨ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "ğŸ› Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "ğŸ§° Maintenance"
    labels:
      - "chore"
      - "refactor"
  - title: "ğŸ“ Documentation"
    labels:
      - "docs"

template: CHANGELOG.tpl.md
